export { connectDatabase, disconnectDatabase } from './client.js';
export {
  repositories,
  addressRepository,
  catalogRepository,
  userRepository,
} from './repositories/index.js';
export type {
  CreateUserInput,
  AddressRow,
  AddressWriteInput,
  AddressUpdateInput,
  CatalogueCategoryRow,
  CatalogueServiceRow,
  CatalogueSortRow,
  SearchActiveServicesParams,
} from './repositories/index.js';

/**
 * Domain enums and row types generated by Prisma, re-exported so application
 * code depends on `@aisbp/database` rather than on the generated client path.
 */
export { Role, BookingStatus, AvailabilitySlotStatus, Prisma } from '../generated/prisma/index.js';

export type {
  User,
  Address,
  ServiceCategory,
  Service,
  Technician,
  AvailabilitySlot,
  Booking,
  BookingStatusHistory,
} from '../generated/prisma/index.js';
