export { connectDatabase, disconnectDatabase } from './client.js';
export {
  repositories,
  addressRepository,
  availabilityRepository,
  bookingRepository,
  catalogRepository,
  operationsRepository,
  technicianRepository,
  userRepository,
} from './repositories/index.js';
export type {
  CreateUserInput,
  AddressRow,
  AddressWriteInput,
  AddressUpdateInput,
  CustomerBookingRow,
  TechnicianBookingRow,
  TechnicianJobRow,
  BookingStatusEventRow,
  CreateBookingData,
  CreateBookingResult,
  CancelBookingResult,
  TechnicianJobStatusResult,
  BookingListSearchParams,
  BookingListSort,
  OperationsTechnicianSummaryRow,
  OperationsTechnicianDetailRow,
  TechnicianSearchParams,
  AddQualificationResult,
  AssignTechnicianResult,
  AssignableTechnicianRow,
  PublicSlotRow,
  TechnicianSlotRow,
  SlotWriteInput,
  SlotWriteResult,
  CatalogueCategoryRow,
  CatalogueServiceRow,
  CatalogueSortRow,
  SearchActiveServicesParams,
  ServicePriceRow,
  OperationsBookingSummaryRow,
  OperationsBookingDetailRow,
  OperationsBookingSearchParams,
  OperationsDashboardCounts,
  OperationsStatusChangeResult,
} from './repositories/index.js';

/**
 * Domain enums and row types generated by Prisma, re-exported so application
 * code depends on `@aisbp/database` rather than on the generated client path.
 */
export { Role, BookingStatus, AvailabilitySlotStatus, Prisma } from '../generated/prisma/index.js';

export type {
  User,
  Address,
  ServiceCategory,
  Service,
  Technician,
  TechnicianService,
  AvailabilitySlot,
  Booking,
  BookingStatusHistory,
} from '../generated/prisma/index.js';
